### ISSUE TITLE
Mysql adapter support

### ISSUE THREAD

**Issue by jneto81** [fragmenta/query#2]
The mysql adapter is missing because is commented

``` go
package adapters

import (
    "database/sql"
    "fmt"

    // Mysql driver
    //_ "github.com/Go-SQL-Driver/MySQL"
)

```

I solve the problem with 

_ "github.com/go-sql-driver/mysql"

its with lowercase.

**Comment by kennygrant** [comment]
Thanks, I'll fix it this weekend, I also need to adjust the tests for recent API changes.

**Comment by kennygrant** [comment]
Thanks for letting me know about this. 

Fixed driver and fixed tests for mysql (required setting &parseTime=true on init for mysql). I'm afraid I've been using almost exclusively psql for the last year, so please let me know if anything else is broken with mysql, or other tests are required.
