### ISSUE TITLE
Adapter Statement Close

### ISSUE THREAD

**Issue by badu** [fragmenta/query#5]
In query/adapters/database.go lines 114 and 141 you have a defer stmt.Close() , despite the fact that you have a comment saying "Caller is responsible for closing rows with defer rows.Close()". This causes runtime errors in fragmenta-cms.

**Comment by kennygrant** [comment]
Apologies for the delay in responding. defer stmt.Close() is not the same as defer rows.Close() is it? We close the statement, then leave the caller to close the rows. Can you paste in the error you saw?
